Objetivo 1
Mapachana/Proyecto-IV pull request #5
Opened 2021-09-26 17:02 UTC by Mapachana

2021-09-26 18:22 UTC, JJ requested changes
Las historias de usuario no son descripciones de usuario, éstas tienen que estar en un documento aparte. Cada tipo de usuario puede generar (y generalmente lo hará) varias historias diferentes.

2021-09-26 18:22 UTC, JJ commented on docs/objetivo1.md
> +| [Consulta de datos e interpretación](https://github.com/Mapachana/Proyecto-IV/milestone/1) | Funcionalidad mínima de la aplicación                        | No empezado   |
Evidentemente la funcionalidad tiene que comenzar por algún lado. Pero
1. Los milestones son productos mínimamente viables. Descríbelos como tales.
2. "Interpretación" es un vocablo bastante ambiguo.

2021-09-26 18:22 UTC, JJ commented on docs/objetivo1.md
> +| [Obtención de gráficas](https://github.com/Mapachana/Proyecto-IV/milestone/2) | Nueva funcionalidad para la obtención de gráficos, mejora de lo anterior | No empezado   |
Descríbelo también en función del producto que se va a publicar. ¿Una biblioteca?¿Un servidor? (para tener un servidor antes tendrás que tener una biblioteca, claro)

2021-09-28 13:30 UTC, Mapachana commented
El PR está listo para revisión

2021-09-28 15:06 UTC, JJ approved these changes
Considero que el objetivo está alcanzado, enhorabuena. Sin embargo, mi principal objeción es que mencionas "aplicación" que "busca". Difícilmente vamos a alcanzar una aplicación en esta asignatura, por lo tanto el producto está descrito con menos precisión de la que debiera. Como es sólo un "nitpick", es algo que puedes ir corrigiendo en los siguientes objetivos.

2021-09-30 07:34 UTC, merged